on:
  push:
    branches:
      - main

name: Publish to Maven Repository

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish"
